apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ankushbanik263/auth
      context: auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

# eval $(minikube docker-env)
# skaffold dev
# minikube tunnel
